### ISSUE TITLE
Error running new example 43

### ISSUE THREAD

**Issue by Othmane-Ch** [OpenSourceRisk/Engine#142]
I have seen that a new example 43 on bonds has been added . I have this error while running it. Anybody has the same error ?

![image](https://user-images.githubusercontent.com/82666104/235713421-21f50d9f-d554-426a-b100-885581ef5fe5.png)

**Comment by noonediesalone** [comment]
It's a QL error, so try updating the submodule:
`git submodule foreach git pull origin master`

**Comment by Othmane-Ch** [comment]
Works perfectly. Thank you

**Comment by Othmane-Ch** [comment]
While I can run the example 43, it doesn't seem to load the trades. I am using the recent version from master.This is my output :

``` 
D:\Desktop\Engine-master\Examples\Example_43>python run.py

1) Run ORE for a single Bond
Loading inputs                                    OK
Requested analytics                               CASHFLOW,EXPOSURE,NPV,XVA
Pricing: Build Market                             OK
Pricing: Build Portfolio
Error: Error in ORE analytics: Portfolio does not contain any built trades, context is 'analytic/PRICING'
Saving plot....Output\mpl_cdf_bond1.pdf
Saving plot....Output\mpl_pdf_bond1.pdf

2) Run ORE for Bond and Swap
Loading inputs                                    OK
Requested analytics                               CASHFLOW,EXPOSURE,NPV,XVA
Pricing: Build Market                             OK
Pricing: Build Portfolio                          OK
Pricing: Cashflow Report                          OK
Pricing: NPV Report                               OK
Pricing: Curves Report                            OK
XVA: Build Market                                 OK

Error: Error in ORE analytics: did not find object 'BOND_AAA' of type default curve under configuration 'collateral_eur' or 'default'
Saving plot....Output\mpl_cdf_bond_swap.pdf
Saving plot....Output\mpl_pdf_bond_swap.pdf

3) Run ORE for 3 Bonds
Loading inputs                                    OK
Requested analytics                               CASHFLOW,EXPOSURE,NPV,XVA
Pricing: Build Market                             OK
Pricing: Build Portfolio
Error: Error in ORE analytics: Portfolio does not contain any built trades, context is 'analytic/PRICING'
Saving plot....Output\mpl_cdf_bond3.pdf
Saving plot....Output\mpl_pdf_bond3.pdf

4) Run ORE for 10 bonds
Loading inputs                                    OK
Requested analytics                               CASHFLOW,EXPOSURE,NPV,XVA
Pricing: Build Market                             OK
Pricing: Build Portfolio
Error: Error in ORE analytics: Portfolio does not contain any built trades, context is 'analytic/PRICING'
Saving plot....Output\mpl_cdf_bond10.pdf
Saving plot....Output\mpl_pdf_bond10.pdf

5) Run ORE for Bond and CDS
Loading inputs                                    OK
Requested analytics                               CASHFLOW,EXPOSURE,NPV,XVA
Pricing: Build Market                             OK
Pricing: Build Portfolio
Error: Error in ORE analytics: Portfolio does not contain any built trades, context is 'analytic/PRICING'
Saving plot....Output\mpl_cdf_bond_cds.pdf
Saving plot....Output\mpl_pdf_bond_cds.pdf
```

**Comment by Othmane-Ch** [comment]
Shoutout  to my boi oussama from Lydex :)

**Comment by quantthingy** [comment]
I just build it from latest master and got similar error on Mac

1) Run ORE for a single Bond
Loading inputs                                    OK
Requested analytics                               CASHFLOW,EXPOSURE,NPV,XVA
Pricing: Build Market                             OK
Pricing: Build Portfolio                          
Error: Error in ORE analytics: Portfolio does not contain any built trades, context is 'analytic/PRICING'
# /opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/__pycache__/__init__.cpython-311.pyc matches /opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/__init__.py
# code object from '/opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/__pycache__/__init__.cpython-311.pyc'
import 'matplotlib.backends' # <_frozen_importlib_external.SourceFileLoader object at 0x10093d810>
# /opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/__pycache__/backend_agg.cpython-311.pyc matches /opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py
# code object from '/opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/__pycache__/backend_agg.cpython-311.pyc'
# extension module 'matplotlib.backends._backend_agg' loaded from '/opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/_backend_agg.cpython-311-darwin.so'
# extension module 'matplotlib.backends._backend_agg' executed from '/opt/homebrew/lib/python3.11/site-packages/matplotlib/backends/_backend_agg.cpython-311-darwin.so'
import 'matplotlib.backends._backend_agg' # <_frozen_importlib_external.ExtensionFileLoader object at 0x12342d950>
import 'matplotlib.backends.backend_agg' # <_frozen_importlib_external.SourceFileLoader object at 0x12342c3d0>
Traceback (most recent call last):
  File "/Volumes/Crucial X6/Documents SSD/ore/Examples/Example_43/run.py", line 15, in <module>
    oreex.plot(targetFileName, 0, 2, 'b', label="Loss")
  File "/Volumes/Crucial X6/Documents SSD/ore/Examples/Example_43/../ore_examples_helper.py", line 115, in plot
    self.ax.plot(self.get_output_data_from_column(filename, colIdxTime, offset),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Crucial X6/Documents SSD/ore/Examples/Example_43/../ore_examples_helper.py", line 99, in get_output_data_from_column
    f = open(os.path.join(os.path.join(os.getcwd(), "Output"), csv_name))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Crucial X6/Documents SSD/ore/Examples/Example_43/Output/credit_migration_bond1_11.csv'

**Comment by quantthingy** [comment]
Still got this error (build it from master on 22 Nov 2023)
1) Run ORE for a single Bond
Loading inputs                                    OK
Requested analytics                               CASHFLOW,EXPOSURE,NPV,XVA
Pricing: Build Market                             OK
Pricing: Build Portfolio                          
Error: Error in ORE analytics: Portfolio does not contain any built trades, context is 'analytic/PRICING'
Traceback (most recent call last):
  File "/Volumes/Crucial X6/Documents SSD/ore/Examples/Example_43/run.py", line 15, in <module>
    oreex.plot(targetFileName, 0, 2, 'b', label="Loss")
  File "/Volumes/Crucial X6/Documents SSD/ore/Examples/Example_43/../ore_examples_helper.py", line 115, in plot
    self.ax.plot(self.get_output_data_from_column(filename, colIdxTime, offset),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Crucial X6/Documents SSD/ore/Examples/Example_43/../ore_examples_helper.py", line 99, in get_output_data_from_column
    f = open(os.path.join(os.path.join(os.getcwd(), "Output"), csv_name))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Crucial X6/Documents SSD/ore/Examples/Example_43/Output/credit_migration_bond1_11.csv'

**Comment by rkapl123** [comment]
Well, this is due to default curve building requiring the additional Eigen3 library, the log says:
`ALERT    [2024-Jan-28 12:19:18.654435] (...ta\ored\marketdata\todaysmarket.cpp:920) : error while building node DefaultCurve(BOND_AAA,Default/EUR/BOND_AAA) in configuration collateral_eur: default curve building failed for BOND_AAA: build attempt failed for BOND_AAA using config with priority 0: Logm(): no implementation provided, you can e.g. install Eigen and rebuild ORE to enable this function.`
There are instructions to install this in the userguide, it works quite well (you have to remove the build cache however), simply install vcpkg [https://vcpkg.io/en/getting-started.html](https://vcpkg.io/en/getting-started.html), then install Eigen3 with `vcpkg install -–triplet x64-windows eigen3` and finally configure ORE cmake build with
```
set VCPKG_ROOT=C:/dev/vcpkg
cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake -DBOOST_INCLUDEDIR=%BOOST% -DBOOST_LIBRARYDIR=%BOOST_LIB64% -DQL_ENABLE_SESSIONS=ON -B build
```

**Comment by rkapl123** [comment]
In general, I would suggest to include Eigen3 and zlib in the prebuilt binary, once this is possible again (see #190 ).

**Comment by quantthingy** [comment]
What about mentioning explicitly the dependency on Eigen3 for all build environment in the doc? (not just windows)

**Comment by rkapl123** [comment]
Actually this is already mentioned in creditmodel.tex (separate doc). I have also included it in the userguide in #242 , line 3140 of userguide.tex.
